# Generated by Django 5.2.2 on 2025-06-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='Organization',
            new_name='Organisation',
        ),
        migrations.RenameField(
            model_name='donors',
            old_name='is_organization',
            new_name='is_organisation',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='is_organization',
            new_name='is_organisation',
        ),
    ]
