# Generated by Django 5.2.2 on 2025-06-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_organization_donors_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='is_individual',
        ),
    ]
