# Generated by Django 5.2.2 on 2025-06-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_donors_is_individual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='Organisation',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='donors',
            old_name='reason_joined',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='donors',
            name='service',
        ),
    ]
